name: Sync Server Folder

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  push_to_other_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Push to WorkiiiServerproduction repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          repository: Amooryjubran/WorkiiiServerproduction
          directory: server
          branch: main
